import unittest
from player import Player
from player_bst import PlayerBST
from player_bnode import PlayerBNode

class MyTests(unittest.TestCase):
    def test_insert(self):
        tree = PlayerBST()
        my_player1 = Player("1", "Alex")
        my_player2 = Player("2", "Brian")
        my_player3 = Player("3", "Charlie")
        my_player4 = Player("4", "Devon")
        my_player5 = Player("5", "Alex")
        my_player6 = Player("6", "Eric")
        tree.root = tree.insert(tree.root, my_player3)
        tree.root = tree.insert(tree.root, my_player1)
        tree.root = tree.insert(tree.root, my_player2)
        tree.root = tree.insert(tree.root, my_player4)
        tree.root = tree.insert(tree.root, my_player5)
        tree.root = tree.insert(tree.root, my_player6)
        self.assertEqual(tree.root.player.name, "Charlie")
        self.assertEqual(tree.root.left.player.name, "Alex")
        self.assertEqual(tree.root.left.right.player.name, "Brian")
        self.assertEqual(tree.root.right.player.name, "Devon")
        self.assertEqual(tree.root.right.right.player.name, "Eric")

    def test_search(self):
        tree = PlayerBST()
        my_player1 = Player("1", "Alex")
        my_player2 = Player("2", "Brian")
        my_player3 = Player("3", "Charlie")
        my_player4 = Player("4", "Devon")
        my_player5 = Player("5", "Alex")
        my_player6 = Player("6", "Eric")
        tree.root = tree.insert(tree.root, my_player3)
        tree.root = tree.insert(tree.root, my_player1)
        tree.root = tree.insert(tree.root, my_player2)
        tree.root = tree.insert(tree.root, my_player4)
        tree.root = tree.insert(tree.root, my_player5)
        tree.root = tree.insert(tree.root, my_player6)
        tree.search(tree.root, "Alex")
        self.assertEqual("Alex", tree.search(tree.root, "Alex").player.name)
        self.assertEqual("5", tree.search(tree.root, "Alex").player.uid)
        self.assertEqual("Charlie", tree.search(tree.root, "Charlie").player.name)
        self.assertEqual("3", tree.search(tree.root, "Charlie").player.uid)
        self.assertEqual("Eric", tree.search(tree.root, "Eric").player.name)
        self.assertEqual("6", tree.search(tree.root, "Eric").player.uid)

    def test_balance(self):
        tree = PlayerBST()
        my_player1 = Player("1", "Alex")
        my_player2 = Player("2", "Brian")
        my_player3 = Player("3", "Charlie")
        my_player4 = Player("4", "Devon")
        my_player5 = Player("5", "Alex")
        my_player6 = Player("6", "Eric")
        my_player7 = Player("7", "Fernandez")
        my_player8 = Player("8", "George")
        my_player9 = Player("9", "Henry")
        my_player10 = Player("10", "Isaac")
        tree.root = tree.insert(tree.root, my_player3)
        tree.root = tree.insert(tree.root, my_player1)
        tree.root = tree.insert(tree.root, my_player2)
        tree.root = tree.insert(tree.root, my_player4)
        tree.root = tree.insert(tree.root, my_player5)
        tree.root = tree.insert(tree.root, my_player6)
        tree.root = tree.insert(tree.root, my_player7)
        tree.root = tree.insert(tree.root, my_player8)
        tree.root = tree.insert(tree.root, my_player9)
        tree.root = tree.insert(tree.root, my_player10)
        tree.root = tree.balance(tree.root)
        self.assertEqual("Eric", tree.root.player.name)
        self.assertEqual("Charlie", tree.root.left.player.name)
        self.assertEqual("Henry", tree.root.right.player.name)
        self.assertEqual("Brian", tree.root.left.left.player.name)
        self.assertEqual("Devon", tree.root.left.right.player.name)
        self.assertEqual("George", tree.root.right.left.player.name)
        self.assertEqual("Isaac", tree.root.right.right.player.name)
        self.assertEqual("Alex", tree.root.left.left.left.player.name)
        # print hierarchy
        #print(tree.root.player)
        #print(tree.root.left.player,"|", tree.root.right.player)
        #print(tree.root.left.left.player, tree.root.left.right.player, "|", tree.root.right.left.player, tree.root.right.right.player)
        #print(tree.root.left.left.left.player)